services:
  mariadb :
    restart : unless-stopped
    build :
      context : requirements/mariadb 
    volumes : 
      - db:/var/lib/mysql 
    networks :
      - net
    env_file :
      - .env
    secrets :
      - DB_PASSWORD

  nginx :
    restart : unless-stopped
    depends_on :
      - wordpress
    build :
      context : requirements/nginx
    volumes :
      - www:/www
    ports:
      - "443:443"
    networks :
      - net
    secrets :
      - franaivo.42.fr-key.pem
      - franaivo.42.fr.pem

  wordpress :
    restart : unless-stopped
    build :
      context : requirements/wordpress      
    depends_on:
      - mariadb
      - redis
    volumes :
      - www:/www
    networks :
      - net
    env_file :
      - .env
    secrets :
      - DB_PASSWORD
      - ADMIN_USER
      - NORMAL_USER

  ftp :
    restart : unless-stopped
    build :
      context : requirements/ftp
    volumes :
      - www:/home/franaivo/www
    networks :
      - net
    ports :
      - "21:21"
      - "21100-21110:21100-21110"
    secrets :
      - ADMIN_USER
      - franaivo.42.fr-key.pem
      - franaivo.42.fr.pem

  redis :
    restart : unless-stopped 
    build :
      context : requirements/redis
    networks :
      - net
    secrets :
      - DB_PASSWORD

  admirer :
    restart : unless-stopped 
    depends_on :
      - mariadb
    build :
      context : requirements/admirer 
    networks :
      - net

  meine :
    restart : unless-stopped 
    build :
      context : requirements/meine 
    networks :
      - net

  cgit :
    restart : unless-stopped 
    build :
      context : requirements/cgit 
    networks :
      - net

networks :
  net :

volumes :
  db :
    driver_opts:
      type: none
      o: bind
      device: /home/franaivo/data/mysql

  www :
    driver_opts:
      type: none
      o: bind
      device: /home/franaivo/data/www


secrets:
  DB_PASSWORD : 
    file : ../secrets/DB_PASSWORD
  ADMIN_USER : 
    file : ../secrets/ADMIN_USER
  NORMAL_USER : 
    file : ../secrets/NORMAL_USER
  franaivo.42.fr-key.pem :
    file : ../secrets/franaivo.42.fr-key.pem
  franaivo.42.fr.pem :
    file : ../secrets/franaivo.42.fr.pem

